tinyMCE.addI18n('tw_utf8.fullpage_dlg',{
title:"文檔屬性",
meta_tab:"一般",
appearance_tab:"外觀",
advanced_tab:"高級",
meta_props:"META 標籤",
langprops:"語言和編碼",
meta_title:"標題",
meta_keywords:"關鍵字",
meta_description:"內容說明",
meta_robots:"Robots",
doctypes:"頁面Doctype",
langcode:"語言編碼",
langdir:"文字排列方式",
ltr:"由左到右",
rtl:"由右到左",
xml_pi:"XML宣告",
encoding:"字元編碼",
appearance_bgprops:"背景屬性",
appearance_marginprops:"Body 對齊方式",
appearance_linkprops:"鏈結顏色",
appearance_textprops:"文本屬性",
bgcolor:"背景顏色",
bgimage:"背景圖片",
left_margin:"左邊界",
right_margin:"右邊界",
top_margin:"上邊界",
bottom_margin:"下邊界",
text_color:"文字顏色",
font_size:"字體尺寸",
font_face:"字體",
link_color:"鏈結顏色",
hover_color:"滑鼠移到鏈結時的顏色",
visited_color:"鏈結被按過後的顏色",
active_color:"鏈結按下去的顏色",
textcolor:"顏色",
fontsize:"字體大小",
fontface:"字型",
meta_index_follow:"索引並跟蹤鏈結",
meta_index_nofollow:"索引但不跟蹤鏈結",
meta_noindex_follow:"不索引但跟蹤鏈結",
meta_noindex_nofollow:"不索引也不跟蹤鏈結",
appearance_style:"樣式表單單及樣式屬性",
stylesheet:"樣式表單單",
style:"樣式",
author:"作者",
copyright:"版權",
add:"增加新元素",
remove:"移除選定元素",
moveup:"上移選定元素",
movedown:"下移選定元素",
head_elements:"Head 元素",
info:"訊息",
add_title:"標題元素",
add_meta:"Meta 元素",
add_script:"Script 元素",
add_style:"Style 元素",
add_link:"Link 元素",
add_base:"Base 元素",
add_comment:"Comment node",
title_element:"搜尋元素",
script_element:"Script 元素",
style_element:"Style 元素",
base_element:"Base 元素",
link_element:"Link 元素",
meta_element:"Meta 元素",
comment_element:"注釋",
src:"Src",
language:"語言",
href:"Href",
target:"目標",
type:"類型",
charset:"編碼charset",
defer:"延緩",
media:"媒體",
properties:"屬性",
name:"名稱",
value:"值",
content:"內容",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"一般",
advanced_props:"高級"
});
