tinyMCE.addI18n('tw_utf8.advlink_dlg',{
title:"插入/編輯 連結",
url:"連結位址",
target:"目標",
titlefield:"查找",
is_email:"您輸入的應該是一個電子郵寄地址，是否需要在網址前加上 mailto: ? ",
is_external:"您輸入的網址應該是一個外部連結，是否需要在網址前加上 http:// ?",
list:"連結清單",
general_tab:"基本",
popup_tab:"快顯視窗",
events_tab:"事件",
advanced_tab:"高級",
general_props:"基本屬性",
popup_props:"快顯視窗屬性",
event_props:"事件",
advanced_props:"高級屬性",
popup_opts:"選項",
anchor_names:"錨點",
target_same:"在當前視窗打開",
target_parent:"在父視窗打開",
target_top:"在頂層視窗打開",
target_blank:"在新視窗打開",
popup:"Javascript 快顯視窗",
popup_url:"彈出窗口位址",
popup_name:"窗口名稱",
popup_return:"插入 'return false'",
popup_scrollbars:"顯示捲軸",
popup_statusbar:"顯示狀態列",
popup_toolbar:"顯示工具列",
popup_menubar:"顯示功能表列",
popup_location:"顯示位址欄",
popup_resizable:"可調整視窗大小",
popup_dependent:"從屬於 ( 僅 Mozilla/Firefox 有效 )",
popup_size:"大小",
popup_position:"座標 (X/Y)",
id:"Id",
style:"樣式",
classes:"樣式類",
target_name:"目標名稱",
langdir:"語言書寫方向",
target_langcode:"目的語言",
langcode:"語言編碼",
encoding:"目的語言編碼",
mime:"目標 MIME 類型",
rel:"rel",
rev:"rev",
tabindex:"Tab索引",
accesskey:"快速鍵",
ltr:"從左到右",
rtl:"從右到左",
link_list:"連結清單"
});
