tinyMCE.addI18n('tw_utf8.table_dlg',{
general_tab:"一般",
advanced_tab:"進階",
general_props:"一般屬性",
advanced_props:"進階屬性",
rowtype:"橫列部份",
title:"插入/更改表格",
width:"寬度",
height:"高度",
cols:"欄",
rows:"行",
cellspacing:"儲存格間距",
cellpadding:"儲存格邊距",
border:"邊框",
align:"對齊",
align_default:"預設",
align_left : '左',
align_right : '右',
align_middle : '中間',
row_title : '橫列屬性',
cell_title : '表格儲存格屬性',
cell_type:"儲存格種類",
valign:"垂直對齊",
align_top:"頂部",
align_bottom:"底部",
bordercolor:"邊框顏色",
bgcolor:"背景顏色",
merge_cells_title:"合拼儲存格",
id:"Id",
style:"Style",
langdir:"語言方向",
langcode:"語言碼",
mime:"目標MIME種類",
ltr:"左至右",
rtl:"右至左",
bgimage:"背景圖片",
summary:"摘要",
td:"儲存格",
th:"頁頭",
cell_cell:"更新這個儲存格",
cell_row:"更新所有在橫列內的儲存格",
cell_all:"更新表格內所有儲存格",
row_row:"更新這個一橫列",
row_odd:"更新表格內所有單數的儲存格",
row_even:"更新表格內所有雙數的儲存格",
row_all:"更新表格內所有儲存格",
thead:"表格頂部",
tbody:"表格主體",
tfoot:"表格底部",
scope:"範圍",
rowgroup:"橫列組",
colgroup:"直欄組",
col_limit:"已超過了最大可設定的欄數量： {$cols} 欄。",
row_limit:"已超過了最大可設定的行數量： {$rows} 行。",
cell_limit:"已超過了最大可設定的儲存格數量 {$cells} 格。",
missing_scope:"你確定在未有指定一個表格頂部的範圍之下繼續嗎？沒有它，一些傷殘人士可能在理解表格的內容或資料時遇上困難。",
caption:"表格標題",
frame:"Frame",
frame_none:"none",
frame_groups:"groups",
frame_rows:"rows",
frame_cols:"cols",
frame_all:"all",
rules:"Rules",
rules_void:"void",
rules_above:"above",
rules_below:"below",
rules_hsides:"hsides",
rules_lhs:"lhs",
rules_rhs:"rhs",
rules_vsides:"vsides",
rules_box:"box",
rules_border:"border"
});
